/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods */

#ifndef _Included_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
#define _Included_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
 * Method:    nativesmartCropAndGrayImage
 * Signature: (Ljava/lang/String;IIFFFFFFFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods_nativesmartCropAndGrayImage
  (JNIEnv *, jobject, jstring, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
 * Method:    nativeGenerateTiffFile
 * Signature: ([Ljava/lang/Object;ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods_nativeGenerateTiffFile
  (JNIEnv *, jobject, jobjectArray, jint, jstring, jstring);

/*
 * Class:     com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
 * Method:    nativeConvertJpg2Faxformat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods_nativeConvertJpg2Faxformat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
 * Method:    nativeRotate
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods_nativeRotate
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods
 * Method:    nativecreateFaxPage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_popfax_mobile_features_edocument_nativemethods_EDocumentNativeMethods_nativecreateFaxPage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
